# Generated by Django 3.2.7 on 2021-09-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.TextField()),
                ('answer_id', models.TextField()),
                ('user', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('useful', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.TextField()),
                ('email', models.CharField(max_length=30)),
                ('user_image', models.TextField(default='default_url')),
                ('post_title', models.TextField()),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.TextField()),
                ('answer_id', models.TextField()),
                ('user', models.CharField(max_length=30)),
                ('replying_to', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
