# Generated by Django 3.2.7 on 2021-09-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_id',
            field=models.TextField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.TextField(unique=True),
        ),
    ]
