# Generated by Django 3.2.7 on 2021-09-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210924_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='user_title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='post_id',
            field=models.TextField(default=''),
        ),
    ]
