# Generated by Django 3.2.7 on 2021-09-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210925_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_image_url',
            field=models.TextField(default='https://t4.ftcdn.net/jpg/00/64/67/63/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju.jpg'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_image_url',
            field=models.TextField(default='https://t4.ftcdn.net/jpg/00/64/67/63/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju.jpg'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user_image_url',
            field=models.TextField(default='https://t4.ftcdn.net/jpg/00/64/67/63/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju.jpg'),
        ),
    ]
