# Generated by Django 3.2.7 on 2021-09-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210925_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='email',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
