# Generated by Django 3.2.7 on 2021-09-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='replying_to',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
