# Generated by Django 3.2.7 on 2021-09-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_reply_replying_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
