# Generated by Django 3.2.7 on 2021-09-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('title', models.TextField(max_length=100)),
                ('full_name', models.TextField(max_length=30)),
                ('stars', models.IntegerField(default=0)),
            ],
        ),
    ]
