# Generated by Django 3.2.7 on 2021-09-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210923_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_user',
            field=models.BooleanField(default=True),
        ),
    ]
