# Generated by Django 3.2.7 on 2021-09-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.TextField(default=''),
        ),
    ]
