# Generated by Django 3.2.7 on 2021-10-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image_url',
            field=models.TextField(default='https://aggred-pictures.s3.ap-south-1.amazonaws.com/profile-pictures/default_profile_image.png'),
        ),
    ]
