# Generated by Django 3.2.7 on 2021-10-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20211007_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voted_answers',
            field=models.TextField(default=''),
        ),
    ]
